#version: '3.9'

services:
    bot:
        # restart: always
        build: .
        container_name: "bot"
        command: bash entrypoint.sh
        depends_on:
        - db_bot
        env_file:
            - .env
    db_bot:
        restart: always
        image: postgres:15
        container_name: "POSTGRES_DB"
        volumes:
        - pg_bot:/var/lib/postgresql/data/
        environment:
            - POSTGRES_HOST=db_bot
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres@stqhJQmh
            - POSTGRES_DB=postgres
        # env_file:
        # - .env

    # pgadmin:
    #     image: dpage/pgadmin4
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
    #         PGADMIN_DEFAULT_PASSWORD: password
    #         PGADMIN_LISTEN_PORT: 80
    #     ports:
    #     - 15432:80
    #     volumes:
    #     - pgadmin:/var/lib/pgadmin
    #     # depends_on:
    #     # - db_bot


volumes:
    pg_bot:
    # pgadmin:
